require('global')
require('configs')
require('plugins')
require('themes')
require('mappings')
require('keymodifiers')

require('lsp')
require('lsp.vim')
require('lsp.go')
require('lsp.python')
require('lsp.bash')
require('lsp.ts-js')
require('lsp.json')
require('lsp.lua')

require('compe-conf')
require('telescope-conf')
require('autopairs-conf')
require('treesitter-conf')
require('galaxyline-conf')
require('nvimtree-conf')
require('gitsigns-conf')
require('dashboard-conf')
require('nvim-ts-autotag')
require('barbar-conf')
