Nmap('f',                ':HopChar1<CR>')
Nmap('<LEADER>w',        ':HopWord<CR>')
Nmap('<LEADER>d',        ':HopChar2<CR>')
Nmap('<LEADER><ESC>',    ':HopLine<CR>')
Nmap('<LEADER><LEADER>', ':HopPattern<CR>')
