-- symbol maps
Icmap(';q', '!')
Icmap(';w', '@')
Icmap(';e', '#')
Icmap(';r', '$')
Icmap(';t', '%')
Icmap(';a', '^')
Icmap(';s', '&')
Icmap(';d', '*')
Icmap(';f', '(')
Icmap(';g', ')')
Icmap(';z', '_')
Icmap(';x', '+')

-- essential maps
Imap(',,', ',<CR>')
Imap(';c', '``<Left>')
Imap(';v', '${}<Left>')

-- number maps
Map('<M-q>', '1')
Map('<M-w>', '2')
Map('<M-e>', '3')
Map('<M-r>', '4')
Map('<M-t>', '5')
Map('<M-a>', '6')
Map('<M-s>', '7')
Map('<M-d>', '8')
Map('<M-f>', '9')
Map('<M-g>', '0')
