-- symbol maps
Icmap(';q', '!', true)
Icmap(';w', '@', true)
Icmap(';e', '#', true)
Icmap(';r', '$', true)
Icmap(';t', '%', true)
Icmap(';a', '^', true)
Icmap(';s', '&', true)
Icmap(';d', '*', true)
Icmap(';f', '(', true)
Icmap(';g', ')', true)
Icmap(';z', '-', true)
Icmap(';x', '=', true)
Icmap(';;z', '_', true)
Icmap(';;x', '+', true)

-- essential maps
-- Imap(',,', ',<CR>')
vim.cmd('inoremap ,, ,<CR>')
Imap(';c', '``<Left>')
Imap(';v', '${}<Left>')
Nmap('<Space>lc', ':<Up>', true)

Cmap('<M-u>', '<Left>', true)
Cmap('<M-i>', '<C-n>', true)
Cmap('<M-o>', '<C-p>', true)
Cmap('<M-p>', '<Right>', true)

-- number maps
Map('<M-q>', '1', true)
Map('<M-w>', '2', true)
Map('<M-e>', '3', true)
Map('<M-r>', '4', true)
Map('<M-t>', '5', true)
Map('<M-a>', '6', true)
Map('<M-s>', '7', true)
Map('<M-d>', '8', true)
Map('<M-f>', '9', true)
Map('<M-g>', '0', true)
